const permissions = {
    CREATE_INSTANT_INVITE: "Create Instant Invite",
    KICK_MEMBERS: "Kick Members",
    BAN_MEMBERS: "Ban Members",
    ADMINISTRATOR: "Administrator",
    MANAGE_CHANNELS: "Manage Channels",
    MANAGE_GUILD: "Manage Guild",
    ADD_REACTIONS: "Add Reactions",
    VIEW_AUDIT_LOG: "View Audit Log",
    PRIORITY_SPEAKER: "Priority Speaker",
    VIEW_CHANNEL: "View Channel",
    READ_MESSAGES: "Read Message",
    SEND_MESSAGES: "Send Messages",
    SEND_TTS_MESSAGES: "Send TTS Messages",
    MANAGE_MESSAGES: "Manage Messages",
    EMBED_LINKS: "Embed Links",
    ATTACH_FILES: "Attach files",
    READ_MESSAGE_HISTORY: "Read Message History",
    MENTION_EVERYONE: "Mention Everyone",
    EXTERNAL_EMOJIS: "External Emojis",
    USE_EXTERNAL_EMOJIS: "User External Emojis",
    CONNECT: "Connect",
    SPEAK: "Speak",
    MUTE_MEMBERS: "Mute Members",
    DEAFEN_MEMBERS: "Deafen Members",
    MOVE_MEMBERS: "Move Members",
    USE_VAD: "Use Vad",
    CHANGE_NICKNAME: "Change Nickname",
    MANAGE_NICKNAMES: "Manage Nicknames",
    MANAGE_ROLES: "Manage Roles",
    MANAGE_ROLES_OR_PERMISSIONS: "Manage Roles Or Permissions",
    MANAGE_WEBHOOKS: "Manage Webhooks",
    MANAGE_EMOJIS: "Manage Emojis" 
};